In [1]:
import numpy as np

# Markovské řetězce

## Diskrétní

https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-14-Slides.pdf

### stacionární rozdělení

https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-15-Slides.pdf

<img src="./img/stacdiskr.png"  width="600"/>

In [40]:
def stac(m, x=4096):
    return np.linalg.matrix_power(m,x)

p = np.array([
    [1/3,1/3,1/3],
    [1/2,1/2,0],
    [0,1,0]
])
p = stac(p)
print(p)
print(p[1]/min(p[1]))

pp = np.array([
    [4/5,1/5],
    [1/2,1/2]
])
pp = stac(pp, 32)
print(pp)
print(pp[1]/min(pp[1]))


[[0.375 0.5   0.125]
 [0.375 0.5   0.125]
 [0.375 0.5   0.125]]
[3. 4. 1.]
[[0.71428571 0.28571429]
 [0.71428571 0.28571429]]
[2.5 1. ]


In [42]:
T = np.array([
    [0, 1/2],
    [1/2, 0]
])
R = np.array([
    [1/2, 0],
    [0, 1/2]
])

N = np.linalg.inv(np.eye(T.shape[0]) - T)
U = N @ R

print(f'{N=}')
print(f'{U=}')

N=array([[1.33333333, 0.66666667],
       [0.66666667, 1.33333333]])
U=array([[0.66666667, 0.33333333],
       [0.33333333, 0.66666667]])


## Spojité

https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-18-Slides.pdf

Q <--> D https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-19-Slides.pdf

Stacionární rozdělení 
https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-20-Slides.pdf

Exponenciální závody
https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-21-Slides.pdf

M Hromadné obsluhy 
https://courses.fit.cvut.cz/NI-VSM/lectures/files/NI-VSM-Lec-22-Slides.pdf

<img src="./img/mm1stac.png"  width="600"/>


In [45]:
n = 10
lmbda = 4
mu = 6
ro = lmbda / mu
pi = []
for i in range(n+1):
    pii = (1-ro) * ro**i
    pi.append(pii)
    print(i, pii)

print(sum(pi))

0 0.33333333333333337
1 0.22222222222222224
2 0.14814814814814817
3 0.09876543209876541
4 0.06584362139917695
5 0.04389574759945129
6 0.029263831732967528
7 0.019509221155311684
8 0.013006147436874454
9 0.008670764957916305
10 0.005780509971944203
0.9884389800561116
